engines:
  csslint:
    enabled: false
  duplication:
    enabled: false
  eslint:
    enabled: true
    checks:
      import/extensions:
        enabled: false
      import/no-extraneous-dependencies:
        enabled: false
    config:
      config: superset/assets/.eslintrc
  pep8:
    enabled: true
  fixme:
    enabled: false
  radon:
    enabled: true
    checks:
      Complexity:
        enabled: false
ratings:
  paths:
  - "**.py"
  - "superset/assets/**.js"
  - "superset/assets/**.jsx"
exclude_paths:
- ".*"
- "**.pyc"
- "**.gz"
- "env/"
- "tests/"
- "superset/assets/images/"
- "superset/assets/vendor/"
- "superset/assets/node_modules/"
- "superset/assets/javascripts/dist/"
- "superset/migrations"
- "docs/"
