language: python
services:
    - redis-server
addons:
  code_climate:
    repo_token: 5f3a06c425eef7be4b43627d7d07a3e46c45bdc07155217825ff7c49cb6a470c
cache:
  directories:
    - $HOME/.wheelhouse/
env:
  global:
    - TRAVIS_CACHE=$HOME/.travis_cache/
    - TRAVIS_NODE_VERSION="7.10.0"
  matrix:
    - TOX_ENV=javascript
    - TOX_ENV=pylint
    - TOX_ENV=py34-postgres
    - TOX_ENV=py34-sqlite
    - TOX_ENV=py27-mysql
    - TOX_ENV=py27-sqlite
before_install:
  - npm install -g npm@'>=5.0.3'
before_script:
  - mysql -e 'drop database if exists superset; create database superset DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci' -u root
  - mysql -u root -e "CREATE USER 'mysqluser'@'localhost' IDENTIFIED BY 'mysqluserpassword';"
  - mysql -u root -e "GRANT ALL ON superset.* TO 'mysqluser'@'localhost';"
  - psql -c 'create database superset;' -U postgres
  - psql -c "CREATE USER postgresuser WITH PASSWORD 'pguserpassword';" -U postgres
  - export PATH=${PATH}:/tmp/hive/bin
install:
  - pip install --upgrade pip
  - pip install tox tox-travis
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
script: tox -e $TOX_ENV
